# MergeHolo default camera config.
# Relative paths are resolved from this file.

camera_config_dir=../00-bin/config/084C
exposure_mode=1
exposure_value=15000
frame_rate=6
capture_rotation=clockwise_90
camera_interface=571
camera_type=Indigo
camera_id=0
gpu_id=0
missed_frame_threshold=100
